spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
server:
  port: 8080
  servlet:
    context-path: "/api"
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
